# Change these first
owner: gnosis93 # Your GitHub organization or username, where this repository lives
repo: UPTIME-WEBECTIVE # The name of this repository

sites:
  - name: Pattaya Interior Designer
    url: https://www.pattayainteriordesigner.com/
  - name: And Burger
    url: https://andburger.in.th/
  - name: Webective
    url: https://webective.com/
  - name: Contracts System
    url: https://contracts.pattayainteriordesigner.com/
  - name: Maps System
    url: https://maps.pattayainteriordesigner.com/login/
  - name: portainer
    url: https://portainer.webective.com/
  - name: kurzus statging
    url: https://kurzus.webective.com/
  - name: kurzus production
    url: https://kurzus.intellident.hu/
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /your-repo-name
  logoUrl: https://webective.com/img/logo-h-active.png
  name: Upptime
  introTitle: "**Webective Upptime** Status page, powered entirely by GitHub."
  introMessage: Webective Managed Websites Uptime Monitor
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
